name: Generate Daily T-Shirts

on:
  schedule:
    - cron: '0 12 * * *'  # Run daily at 12 PM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-tees:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run t-shirt generation
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PRINTFUL_API_TOKEN: ${{ secrets.PRINTFUL_API_TOKEN }}
        SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
        SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
        SHOPIFY_STORE_NAME: ${{ secrets.SHOPIFY_STORE_NAME }}
      run: python3 ./generate_tee.py
      
    - name: Commit updated collections.json if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add collections.json || true
        git diff --staged --quiet || git commit -m "Update collections.json [skip ci]" || true
        git push || true
