name: Generate T-Shirt Design

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 10 * * *'  # Daily at 10 AM UTC

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create collections.json if missing
      run: |
        if [ ! -f collections.json ]; then
          echo "Creating collections.json..."
          python seed_collections.py
        else
          echo "collections.json already exists"
        fi
    
    - name: Run T-Shirt Generator
      env:
        # Pass secrets as environment variables
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PRINTFUL_API_KEY: ${{ secrets.PRINTFUL_API_KEY }}
        PRINTFUL_STORE_ID: ${{ secrets.PRINTFUL_STORE_ID }}
        SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
        SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
        MARKUP_PERCENT: ${{ secrets.MARKUP_PERCENT }}
      run: |
        echo "Starting T-shirt generation..."
        python generate_tee.py
    
    - name: Upload logs and images
      if: always()
      uses: actions/upload-artifact@v4  # Using v4 to fix the error
      with:
        name: generation-output
        path: |
          tshirt_generator.log
          *.png
        retention-days: 7
