name: Generate T-Shirt Design

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create collections.json if missing
      run: |
        if [ ! -f collections.json ]; then
          if [ -f seed_collections.py ]; then
            python seed_collections.py
          else
            # Create a basic collections.json
            echo '{
              "general": {
                "name": "General Designs",
                "title": "AI T-Shirt Design",
                "theme": "Creative and unique t-shirt design",
                "tags": ["creative", "unique", "ai"]
              }
            }' > collections.json
          fi
        fi
    
    - name: Run T-Shirt Generator
      env:
        # THIS IS THE CRITICAL PART - PASS SECRETS AS ENV VARS
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PRINTFUL_API_KEY: ${{ secrets.PRINTFUL_API_KEY }}
        PRINTFUL_STORE_ID: ${{ secrets.PRINTFUL_STORE_ID }}
        SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
        SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
        MARKUP_PERCENT: ${{ secrets.MARKUP_PERCENT }}
      run: |
        echo "Starting T-shirt generation..."
        python generate_tee.py
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: |
          tshirt_generator.log
          *.png
