name: Generate T-Shirt Design

on:
  # Manual trigger
  workflow_dispatch:
  
  # Automatic triggers
  push:
    branches: [ main ]
  
  # Daily at 10 AM UTC
  schedule:
    - cron: '0 10 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        # Upgrade pip
        python -m pip install --upgrade pip
        
        # Force install correct versions (bypasses cache)
        pip install --force-reinstall --no-cache-dir openai==1.12.0 requests==2.31.0 Pillow==10.0.0
        
        # Verify OpenAI version
        python -c "import openai; print(f'OpenAI version installed: {openai.__version__}')"
    
    - name: Run T-Shirt Generator
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PRINTFUL_API_KEY: ${{ secrets.PRINTFUL_API_KEY }}
        PRINTFUL_STORE_ID: ${{ secrets.PRINTFUL_STORE_ID }}
        SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
        SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
        MARKUP_PERCENT: ${{ secrets.MARKUP_PERCENT }}
      run: |
        echo "🚀 Starting T-shirt generation..."
        echo "📍 Using Store ID: $PRINTFUL_STORE_ID"
        python generate_tee.py
    
    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: generation-results-${{ github.run_number }}
        path: |
          tshirt_generator.log
          *.png
        retention-days: 7
