name: Manual T-Shirt Generation

on:
  workflow_dispatch:
    inputs:
      category:
        description: 'Category (e.g., gaming, coffee, fitness) - leave empty for random'
        required: false
        type: string
        default: ''
      count:
        description: 'Number of designs to generate'
        required: false
        type: string
        default: '1'
      delay:
        description: 'Delay between generations (seconds)'
        required: false
        type: string
        default: '5'

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate T-Shirts
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PRINTFUL_API_KEY: ${{ secrets.PRINTFUL_API_KEY }}
        PRINTFUL_STORE_ID: ${{ secrets.PRINTFUL_STORE_ID }}
        SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
        SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
        MARKUP_PERCENT: ${{ secrets.MARKUP_PERCENT }}
      run: |
        if [ "${{ inputs.count }}" = "1" ] && [ -z "${{ inputs.category }}" ]; then
          echo "🎲 Generating single random design..."
          python generate_tee.py
        elif [ -n "${{ inputs.category }}" ]; then
          echo "🎯 Generating ${{ inputs.count }} design(s) for category: ${{ inputs.category }}"
          python bulk_generate.py --count ${{ inputs.count }} --categories "${{ inputs.category }}" --delay ${{ inputs.delay }}
        else
          echo "🎨 Generating ${{ inputs.count }} random designs..."
          python bulk_generate.py --count ${{ inputs.count }} --delay ${{ inputs.delay }}
        fi
    
    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: manual-generation-${{ github.run_number }}
        path: |
          tshirt_generator.log
          *.png
        retention-days: 7
